// <auto-generated />
namespace FootballLeague.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class teamscoretableadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(teamscoretableadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202010171011451_team-score-table-added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
